sudo: required
services:
  - docker

before_install:
  - docker build -t niteshks/react-test -f ./client/Dockerfile.dev ./client
  # We can add tests for other components as well such as server, worker etc.

script:
  - docker run -e CI=true niteshks/react-test npm test -- --coverage


after_success:
  - docker build -t niteshks/multiservice-client ./client
  - docker build -t niteshks/multiservice-nginx ./nginx
  - docker build -t niteshks/multiservice-server ./server
  - docker build -t niteshks/multiservice-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to docker hub
  - docker push niteshks/multiservice-client
  - docker push niteshks/multiservice-nginx
  - docker push niteshks/multiservice-server
  - docker push niteshks/multiservice-worker
