apiVersion: v1
kind: Service
metadata: 
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    # Tells the cluster ip service which component it 
    # provides access to
    component: server
  ports:
    - port: 5000
      targetPort: 5000